[package]
name = "petshop"
version = "0.1.0"
edition = "2021"

[dependencies]
api-gen-macro = { path = "../api-gen-macro" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
